// vue/components/ParallaxTemplate/Header/Item.vue
<template>
	<a :href="href" :class="`item ${className}`">
		<FontAwesomeIcon v-if="icon" :icon="icon" />
		<slot />
	</a>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'nuxt-property-decorator';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { IconDefinition } from '@fortawesome/free-solid-svg-icons';

@Component({ components: { FontAwesomeIcon } })
export default class Item extends Vue {
	@Prop({ default: '#' }) href?: string;
	@Prop() className?: string;
	@Prop() icon?: IconDefinition;
}
</script>

<style lang="sass"></style>

// react/components/ParallaxTemplate/Header/Item.tsx
import Link from 'next/link';
import { ReactElement } from 'react';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import style from './header.module.sass';

type Props = {
	href: string;
	text?: string;
	className?: string;
	icon?: IconDefinition;
};

const Item = ({
	href,
	text = '',
	className = '',
	icon = null,
}: Props): ReactElement => {
	const { item } = style;

	return (
		<Link href={href}>
			<a className={`${item} ${className}`}>
				{icon ? <FontAwesomeIcon icon={icon} /> : null}
				{text}
			</a>
		</Link>
	);
};

export default Item;
