// react/components/ParallaxTemplate/Info.tsx
import { ReactElement } from 'react';

import style from './styles/info.module.sass';

const Info = (): ReactElement => {
	const { info, info_block, info_block_title, info_block_subtitle } = style;

	const Block = (amount: string, text: string): ReactElement => (
		<div className={info_block}>
			<p className={info_block_title}>{amount}</p>
			<p className={info_block_subtitle}>{text}</p>
		</div>
	);

	return (
		<div className={info}>
			{Block('14+', 'Partners')}
			{Block('55+', 'Web Design')}
			{Block('89+', 'Happy Clients')}
			{Block('150+', 'Meetings')}
		</div>
	);
};

export default Info;

// vue/components/ParallaxTemplate/Info/index.vue
<template>
	<div class="info">
		<Block amount="14+" text="Partners" />
		<Block amount="55+" text="Web Design" />
		<Block amount="89+" text="Happy Clients" />
		<Block amount="150+" text="Meetings" />
	</div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator';
import Block from './Block.vue';

@Component({ components: { Block } })
export default class Info extends Vue {}
</script>

<style lang="sass">
$back: #616161
$color: white

.info
    width: 100%
    background: $back
    color: $color
    display: flex
    justify-content: space-around
</style>
